import Head from "next/head";
import {
  AiFillLinkedin,
  AiFillGithub,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import { pdfjs } from "react-pdf";
import deved from "../public/peepsAvatar.png";
import Image from "next/image";
import BarkBoard from '../public/images/BarkBoard.png'
import Jobbr3d from '../public/images/Jobbr3d.png'
import Ribbit from '../public/images/Ribbit.png'
import SpaceMan from '../public/images/SpaceMan.png'

pdfjs.GlobalWorkerOptions.workerSrc = `//cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjs.version}/pdf.worker.min.js`

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  const [showParagraph1, setShowParagraph1] = useState(true)

  const [showParagraph2, setShowParagraph2] = useState(true)

  const [showParagraph3, setShowParagraph3] = useState(true)

  const [showParagraph4, setShowParagraph4] = useState(true)

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Patrick Mangan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">patrick mangan</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
      
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Patrick Mangan
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Software Engineer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Budding software engineer born and raised in Washington DC, who is a determined and curious learner, and an absolute 3d printing fanatic. As public relations and graphic design professional, I relied on my research, strategy, and a keen eye for detail to solve problems. I will use my same fanaticism for 3d printing and pour it into programming your web application! I have a unique ability to visualize and sort data into visually appealing and simple inputs for users. My experience includes bringing a brand to life through intuitive design, and exceeding growth expectations. Check my links down below and get started!
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <AiFillLinkedin />
              <AiFillGithub />
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={deved} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl text-center py-1 dark:text-white ">Portofolio</h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Since transitioning careers, I have built multiple projects as you can see below. Hover/Tap on the project to find out more!
            </p>
          </div>

          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 " onMouseOver={() => setShowParagraph1(false)}
              onMouseOut={() => setShowParagraph1(true)}>
              {showParagraph1 ? (
                <Image
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  alt={"bark board"}
                  layout="responsive"
                  src={BarkBoard}
                />
              ) : (
                <>
                <p className ="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl"> BarkBoard is the ultimate community forum for pet owners who want to connect, share experiences, and seek advice on pet ownership. Whether you are a seasoned pet owner or new to the world of pets, BarkBoard offers a supportive and informative platform where pet owners can come together to share their love for pets. With Bark Board, you can ask for advice, share tips, and learn from other pet owners who have been through similar experiences. So, whether you have a question about pet nutrition, training, or behavior, BarkBoard has got you covered. Join the BarkBoard community today and become a part of a fun and supportive network of pet lovers!</p>
                <a
                className="flex justify-center items-center bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md text-center"
                href="https://bark-board-client.onrender.com/"
              >
                Check it Out!
              </a>
              </>
              )}
            </div>

            <div className="basis-1/3 flex-1" onMouseEnter={() => setShowParagraph2(false)}
              onMouseLeave={() => setShowParagraph2(true)}>
              {showParagraph2 ? (
                <Image
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  alt={"jobber 3d"}
                  layout="responsive"
                  src={Jobbr3d}
                />
              ) : (
                <>
                <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">Jobbr3d is the ultimate app for 3D printing enthusiasts who want to turn their hobby into a small business. With Jobbr3d, you can keep track of your customers and assign print jobs to them, all in one convenient place. As you grow your business, the app will evolve with you, including features like inventory management for materials and other consumables, making it even easier to manage your operation. Additionally, Jobbr3d  will incorporate Octoprint, which will allow you to remotely manage your printer and monitor print progress, making your 3D printing process even more streamlined.</p>
                <a
                className="flex justify-center items-center bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md text-center"
                href="https://npm-install-andand-npm-run-build-mnbj.onrender.com/"
              >
                Check it Out!
              </a>
              </>
              )}
            </div>

            <div className="basis-1/3 flex-1" onMouseEnter={() => setShowParagraph3(false)}
              onMouseLeave={() => setShowParagraph3(true)}>
              {showParagraph3 ? (
                <Image
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  alt={"SpaceMan"}
                  layout="responsive"
                  src={SpaceMan}
                />
              ) : (
                <>
                <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">Spaceman is an exciting word-guessing game that challenges players to guess a mystery word by filling up a rocket with fuel. It is a fun and engaging way to improve your vocabulary and language skills. Suitable for players of all ages and backgrounds, Spaceman offers a modern take on the classic word-guessing game. So, come join the space mission and see how far you can go in Spaceman!</p>
                <a
                className="flex justify-center items-center bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md text-center"
                href="https://patmangan98.github.io/Project1/"
              >
                Check it Out!
              </a>
              </>
              )}
            </div>

            <div className="basis-1/3 flex-1"
              onMouseEnter={() => setShowParagraph4(false)}
              onMouseLeave={() => setShowParagraph4(true)}>

              {showParagraph4 ? (
                <Image
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  title="sample text"
                  src={Ribbit}
                />
              ) : (
                <>
                <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">Ribbit is the perfect app for hobbyists who want to connect and share their passion with like-minded enthusiasts. Ribbit offers a platform where users can start threads on their favorite topics and connect with other hobbyists who share the same interests. With Ribbit, you can post within threads, comment on other users' posts, and engage in meaningful discussions with other enthusiasts. Whether you're interested in crafting, cooking, or collecting, Ribbit has a wide range of topics to choose from. So, join the Ribbit community today and start sharing your passion with the world!</p>

                <a
                className="flex justify-center items-center bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md text-center"
                href="https://npm-install-andand-npm-run-build-mnbj.onrender.com/"
              >
                Check it Out!
              </a>
              </>
              )}
            </div>
          </div>
        </section>
            <section>
              <div className="py-10 text-center">
                <h3 className ="text-xl py-12 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">Resume</h3>
                <iframe  width ="100%" height="500px"src="/images/NewResume2023.pdf"/>
              </div>
            </section>
      </main>
    </div>
  );
}
